{% set version = "2.2.21" %}

package:
    name: udunits2
    version: {{ version }}

source:
    fn: udunits-{{ version }}.tar.gz
    url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-{{ version }}.tar.gz
    sha1: 4afc6d767d38e720f2898674e09dc3720a4b131e

build:
    number: 0
    detect_binary_files_with_prefix: true
    features:
      - vc9  # [win and py27]
      - vc10  # [win and py34]
      - vc14  # [win and py>=35]


requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - expat  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - expat  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
    commands:
        - udunits2 -h
        - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: https://github.com/Unidata/UDUNITS-2/blob/master/COPYRIGHT
  summary: The UDUNITS package supports units of physical quantities.
